cors:
  originPatterns: http://localhost:3000,http://localhost:4200,http://localhost:8080

app:
  storage:
    service-order-photos: /var/lib/my-application/service-order-photos
    
spring:
  main:
    allow-circular-references: true
  application:
    name: fiber_splice_locator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-da2qagon74is738girdg-a:5432/fiber_splice_locator
    username: fiber_splice_locator_user
    password: C2uyC9elAF9SY2XIbWxCl3TfgdZrmxrz
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  profiles:
    active: prod


security:
  jwt:
    secret: fiber-splice-locator-secret-key-2026
    expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
  api-docs:
    enabled: true